version: '2'
services:
  blog:
    image: httpd:2.4
    container_name: lifescope_blog
    volumes:
      - ./docs:/usr/local/apache2/htdocs/
    restart: "always"
    environment:
      - VIRTUAL_HOST=insights.lifescope-project.com
      - LETSENCRYPT_EMAIL=jdonado@jdonado.com
      - LETSENCRYPT_HOST=insights.lifescope-project.com
    networks:
      - jdonado-nw
    expose:
      - 8888

networks:
  jdonado-nw:
    external:
      name: jdonado-nw
